#!/usr/bin/bash

# import -
configPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
bin="$configPath/bin"
. $bin/xdate

# notes -
  # work-on
    # Standby

# code -
  # preferences -
    alias ll="ls -lF --color"
    alias lall="ls -alF --color"
    alias lal="lall"
    alias del="echo \"rm -rf\" "$1""
  # git -
    alias glog='git log --oneline --decorate --graph --all'
  # python -
    alias howWheel="echo 'python setup.py sdist bdist_wheel'"
    alias piping="echo 'pip freeze | xargs pip uninstall -y'"
